name: Build

permissions:
  contents: write

on:
  push:
    tags:
      - v*.*.*

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        architecture: ['x86', 'x64']

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        architecture: ${{ matrix.architecture }}

    - name: Install dependencies
      run: |
        choco install upx
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build with PyInstaller
      run: |
        pyinstaller -Fw main.pyw
        copy dist/*.exe .
        7z a TrayWP-${{ matrix.architecture }}.zip *.exe

    - name: Create GitHub release
      uses: softprops/action-gh-release@v1
      with:
        generate_release_notes: true
        files: TrayWP-${{ matrix.architecture }}.zip
