name: Build

on:
  push:
    tags:
      - v*.*.*

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        architecture: 'x86'

    - name: Install dependencies
      run: |
        choco install upx
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build with PyInstaller
      run: |
        pyinstaller -Fw main.pyw
        copy dist/*.exe .
        7z a TrayWP-x86.zip *.exe

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        choco install upx
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build with PyInstaller
      run: |
        pyinstaller -Fw main.pyw
        copy dist/*.exe .
        7z a TrayWP-x86_64.zip *.exe

    - name: Create GitHub release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          TrayWP-x86.zip
          TrayWP-x86_64.zip
